inherit SKILL;

mapping *quest = ({
	([      "quest":                "Ð¡º¢",
		"quest_type":           "É±",
		"time":                 15,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Å£Æ¤¾Æ´ü",
		"quest_type":           "Ñ°",
		"time":                 5,
		"exp_bonus":            10,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ÄÐº¢",
		"quest_type":           "É±",
		"time":                 10,
		"exp_bonus":            15,
		"pot_bonus":            10,
		"score" :               20
	]),
	([      "quest":                "¿¾¼¦ÍÈ",
		"quest_type":           "Ñ°",
		"time":                 10,
		"exp_bonus":            10,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Å©Ãñ",
		"quest_type":           "É±",
		"time":                 25,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "´å¹Ã",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Ñ¾»·",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            25,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Å®º¢",
		"quest_type":           "É±",
		"time":                 35,
		"exp_bonus":            30,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "½ð»·Éß",
		"quest_type":           "É±",
		"time":                 20,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "°×ÒÂÉÙÅ®",
		"quest_type":           "É±",
		"time":                 35,
		"exp_bonus":            30,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ÕÅÂè",
		"quest_type":           "É±",
		"time":                 35,
		"exp_bonus":            40,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "°×ÍÃ",
		"quest_type":           "É±",
		"time":                 20,
		"exp_bonus":            10,
		"pot_bonus":             5,
		"score" :                5
	]),
	([      "quest":                "·ëÌú½³",
		"quest_type":           "É±",
		"time":                 15,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
       ([      "quest":                "ÐÇËÞÅÉºÅÊÖ",
		"quest_type":           "É±",
		"time":                 60,
		"exp_bonus":            50,
		"pot_bonus":            10,
		"score" :               5
	]),
       ([      "quest":                "ÐÇËÞÅÉîàÊÖ",
		"quest_type":           "É±",
		"time":                 55,
		"exp_bonus":            30,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Ìô·ò",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ÐÇËÞÅÉ¹ÄÊÖ",
		"quest_type":           "É±",
		"time":                 80,
		"exp_bonus":            40,
		"pot_bonus":            15,
		"score" :                5
	]),
	([      "quest":                "ÄÁÑòÅ®",
		"quest_type":           "É±",
		"time":                 40,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Î¬Îá¶û×å¸¾Å®",
		"quest_type":           "É±",
		"time":                 40,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "°¢·²Ìá",
		"quest_type":           "É±",
		"time":                 45,
		"exp_bonus":            25,
		"pot_bonus":            10,
		"score" :                5
	]),
	([      "quest":                "³¤½£",
		"quest_type":           "Ñ°",
		"time":                 20,
		"exp_bonus":            10,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "´óÀÇ¹·",
		"quest_type":           "É±",
		"time":                 20,
		"exp_bonus":            10,
		"pot_bonus":            10,
		"score" :               10
	]),
	([      "quest":                "¼Ò¶¡",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ÑÃÒÛ",
		"quest_type":          "É±",
		"time":                30,
		"exp_bonus":           30,
		"pot_bonus":           10,
		"score" :               5
	]),
	([      "quest":                "Öª¿ÍÉ®",
		"quest_type":           "É±",
		"time":                 40,
		"exp_bonus":            20,
		"pot_bonus":            5,
		"score" :               10
	]),
	([      "quest":                "Á÷Ã¥",
		"quest_type":           "É±",
		"time":                 20,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Ò°¹·",
		"quest_type":           "É±",
		"time":                 15,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	]),
       ([      "quest":                "ÄÁÑò±Þ",
		"quest_type":           "Ñ°",
		"time":                 60,
		"exp_bonus":            15,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ÄÐº¢",
		"quest_type":           "É±",
		"time":                 15,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	]),
	([      "quest":                "ÀÏ´óÄï",
		"quest_type":           "É±",
		"time":                 50,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "µØÆ¦",
		"quest_type":           "É±",
		"time":                 25,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Ð¡Á÷Ã¥",
		"quest_type":           "É±",
		"time":                 20,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	 ]),
	 ([      "quest":                "ÓÎ¿Í",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	]),
	([      "quest":                "Ò©ÆÌ»ï¼Æ",
		"quest_type":           "É±",
		"time":                 10,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	]),
	([      "quest":                "Ð¡¹ð×Ó",
		"quest_type":           "É±",
		"time":                 10,
		"exp_bonus":            10,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ºï×Ó",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            20,
		"pot_bonus":            5,
		"score" :               5
	]),
	([      "quest":                "½øÏã¿Í",
		"quest_type":           "É±",
		"time":                 30,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :                5
	]),
	([      "quest":                "µÀÍ¯",
		"quest_type":           "É±",
		"time":                 60,
		"exp_bonus":            30,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "ÀÇ",
		"quest_type":           "É±",
		"time":                 50,
		"exp_bonus":            20,
		"pot_bonus":            10,
		"score" :               5
	]),
	([      "quest":                "Ð¡··",
		"quest_type":           "É±",
		"time":                 70,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	]),
	([      "quest":                "ÊéÉú",
		"quest_type":           "É±",
		"time":                 60,
		"exp_bonus":            10,
		"pot_bonus":            5,
		"score" :               5
	]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}

