mapping guainame = ([

"魔":
     (["张四":({"zhang si","zhang"}),
       "上官清月":({"shangguan qingyue","shangguan"}),
       "龙风刹":({"long fengsha","long"}),
       "王三":({"wang san","wang"}),
       "西门崇航":({"ximen chonghang","ximen"}),
       "李五":({"li wu","li"}),
       "慕容秋迅":({"murong qiuxun","murong"}),
       "刘大":({"liu da","liu"}),
       "慕容天成":({"murong tiancheng","murong"}),
       "风二":({"feng er","feng"}),
       "欧阳剑心":({"ouyang jianxin","ouyang"}),
       "赵六":({"zhao liu","zhao"}),
       "欧阳松":({"ouyang song","ouyang"}),
       "上官空觉":({"shangguan kongjue","shangguan"}),
       "周七":({"zhou qi","zhou"}),
       "南宫宛清":({"nangong wanqing","nangong"}),
       "吴八":({"wu ba","wu"}),
       "南宫雀":({"nangong que","nangong"}),
       "郑九":({"zheng jiu","zheng"}),
       "上官天":({"shangguan tian","shangguan"}),
       "蹩十":({"bie shi","bie"}),
       "上官云":({"shangguan yun","shangguan"}),
       "郭风":({"guo feng","guo"}),
       "张月星":({"zhang yuexing","zhang"}),
       "郑化":({"zheng hua","zheng"}),
       "周空如":({"zhou kongru","zhou"}),
       "黎白":({"li bai","li"}),
       "周长空":({"zhou changkong","zhou"}),
       "莫大":({"mo da","mo"}),
       "黎生":({"li sheng","li"}),
       "唐西经":({"tang xijing","tang"}),
       "猪凤天":({"zhu fengtian","zhu"}),
       "孙霸":({"sun ba","sun"}),
       "李霸":({"li ba","li"}),
       "雄霸":({"xiong ba","xiong"}),
       "公孙不二":({"gongsun buer","gongsun"}),
       "公孙无敌":({"gongsun wudi","gongsun"}),
       "司马康":({"sima kang","sima"}),
       "全无敌":({"quan wudi","quan"}),
       "上官钱清":({"shangguan qianqing","shangguan"}),
       "欧阳星如":({"ouyang xingru","ouyang"}),
      ]),
]);
          

mapping guai_name1 = ([
	"龙"   : "long",
	"柴"   : "cai",
	"居"   : "ju",
	"连"   : "lian",
	"盛"   : "sheng",
	"伊"   : "yi",
	"满"   : "man",
	"沙"   : "sha",
	"东"   : "dong",
	"冷"   : "leng",
	"解"   : "jie",
	"却"   : "que",
	"艾"   : "ai",
	"乔"   : "qiao",
	"广"   : "guang",
	"相"   : "xiang",
	"仇"   : "chou",
	"车"   : "che",
	"赖"   : "lai",
	"山"   : "shan",
	"邹"   : "zhou",
	"燕"   : "yan",
	"阮"   : "yuan",
	"叶"   : "ye",
	"计"   : "ji",
	"舒"   : "shu",
	"卓"   : "zhuo",
	"洪"   : "hong",
	"能"   : "neng",
	"米"   : "mi",
	"李"   : "li",
	"陈"   : "chen",
	"肖"   : "xiao",
	"彭"   : "peng",
	"上官" : "shangguan",
	"步"   : "bu",
	"聂"   : "nie",
	"令狐" : "linghu",
	"欧阳" : "ouyang",
	"慕容" : "murong",
	"猪"   : "zhu",
	"牛"   : "niu",
	"狗"   : "gou",
	"司徒" : "situ",
	"司马" : "sima",
	"全"   : "quan",
	"鞠"   : "ju",
	"曹"   : "cao",
	"南宫" : "nangong",
	"公孙" : "gongsun",
	"胡"   : "hu",
	"西门" : "ximen",
	"孙"   : "sun",
	"刘"   : "liu",
	"张"   : "zhang",
	"赵"   : "zhao",
	"魏"   : "wei",
	"王"   : "wang",
	"黄"   : "huang",
	"吴"   : "wu",
	"郑"   : "zheng",
	"郭"   : "guo",
	"黎"   : "li",
	"唐"   : "tang",
	"莫"   : "mo",
	"田"   : "tian",
	"岳"   : "yue",
	"秦"   : "qin",
	"宁"   : "ning",
	"宋"   : "song",
	"于"   : "yu",
	"俞"   : "yu",
	"罗"   : "luo",
	"涂"   : "tu",
	"冯"   : "feng",
	"奉"   : "feng",
	"温"   : "wen",
	"万"   : "wan",
	"钱"   : "qian",
	"夏侯" : "xiahou",
	"诸葛" : "zhuge",
	"公冶" : "gongzhi",
	"司空" : "sikong",
	"宇文" : "yuwen",
	"太叔" : "taishu",
	"公羊" : "gongyang",
	"闻人" : "wenren",
	"宗政" : "zongzheng",
	"关"   : "guan",
	]);

mapping guai_name2 = ([
	"风" : "feng",
	"封" : "feng",
	"逢" : "feng",
	"蜂" : "feng",
	"丰" : "feng",
	"枫" : "feng",
	"讽" : "feng",
	"里" : "li",
	"娃" : "wa",
	"沃" : "wo",
	"宛" : "wan",
	"棉" : "mian",
	"签" : "qian",
	"迁" : "qian",
	"光" : "guang",
	"婷" : "ting",
	"钎" : "qian",
	"芡" : "qian",
	"散" : "san",
	"闪" : "shan",
	"晌" : "shang",
	"桑" : "sang",
	"宽" : "kuan",
	"况" : "kuang",
	"埋" : "mai",
	"蔓" : "man",
	"氓" : "mang",
	"键" : "jian",
	"僵" : "jiang",
	"粘" : "zhan",
	"掌" : "zhang",
	"昝" : "zan",
	"掌" : "zhang",
	"弥" : "mi",
	"蠛" : "mie",
	"缅" : "mian",
	"筏" : "fa",
	"帆" : "fan",
	"访" : "fang",
	"嚓" : "ca",
	"差" : "cha",
	"惭" : "can",
	"伧" : "cang",
	"搀" : "chan",
	"尝" : "chang",
	"雨" : "yu",
	"韵" : "yun",
	"原" : "yuan",
	"弩" : "nu",
	"拗" : "niu",
	"墨" : "mo",
	"侔" : "mou",
	"墓" : "mu",
	"蜡" : "la",
	"栏" : "lan",
	"浪" : "lang",
	"娜" : "na",
	"囡" : "nan",
	"囔" : "nang",
	"绵" : "mian",
	"既" : "ji",
	"今" : "jin",
	"惊" : "jing",
	"区" : "qu",
	"麇" : "qun",
	"浮" : "fu",
	"嘎" : "ga",
	"竿" : "gan",
	"刚" : "gang",
	"搭" : "da",
	"弹" : "dan",
	"荡" : "dang",
	"苦" : "ku",
	"舞" : "wu",
	"戏" : "xi",
	"峡" : "xia",
	"突" : "tu",
	"囤" : "tun",
	"软" : "ruan",
	"虹" : "hong",
	"飞" : "fei",
	"规" : "gui",
	"恶" : "wu",
	"化" : "hua",
	"盖" : "gai",
	"幅" : "fu",
	"河" : "he",
	"斯" : "si",
	"羽" : "yu",
	"速" : "su",
	"畅" : "chang",
	"舒" : "shu",
	"迩" : "er",
	"颇" : "po",
	"梵" : "fan",
	"乜" : "mie",
	"星" : "xing",
	"蒙" : "meng",
	"华" : "hua",
	"成" : "cheng",
	"辉" : "hui",
	"皇" : "wang",
	"海" : "hai",
	"奇" : "qi",
	"强" : "qiang",
	"钟" : "zhong",
	]);