mapping *quest = ({
     ([      "quest":                "骰子",
        "diff":                 5,
        ]),
     ([      "quest":                 "腹蛇胆" ,
        "diff":                 4,
        ]),
     ([      "quest":                HIG "百香花" NOR,
        "diff":                 8,
        ]),
     ([      "quest":                "无名花",
        "diff":                 7,
        ]),
     ([      "quest":                HIW "夜明珠" NOR,
        "diff":                 6,
        ]),
     ([      "quest":                "游龙剑",
        "diff":                 5,
        ]),
     ([      "quest":                "天山六阳掌法图上册",
        "diff":                 5,
        ]),
     ([      "quest":                "天山六阳掌法图下册",
        "diff":                 5,
        ]),
     ([      "quest":                "天山折梅手法图下卷",
        "diff":                 10,
        ]),
     ([      "quest":                "天山折梅手法图上卷",
        "diff":                 6,
        ]),
     ([      "quest":                "白云熊胆丸",
        "diff":                 10,
        ]),
     ([      "quest":                "海底金母",
        "diff":                 20,
        ]),
     ([      "quest":                "寒丝羽竹",
        "diff":                 20,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
