mapping *quest = ({
     ([      "quest":                "…ﬂµ®∏‡",
        "diff":                 2,
        ]),
     ([      "quest":                "√Êæﬂ",
        "diff":                 2,
        ]),
     ([      "quest":                "”ÒœÙ",
        "diff":                 8,
        ]),
     ([      "quest":                "◊œΩ¥∏",
        "diff":                 2,
        ]),
     ([      "quest":                "∑Á¿◊Ã√¡Ó≈∆",
        "diff":                 4,
        ]),
     ([      "quest":                "∞◊ª¢Ã√¡Ó≈∆",
        "diff":                 4,
        ]),
     ([      "quest":                "«‡¡˙Ã√¡Ó≈∆",
        "diff":                 3,
        ]),
     ([      "quest":                "ÃÏœ„Ã√¡Ó≈∆",
        "diff":                 3,
        ]),
     ([      "quest":                "ø˚ª®’Î",
        "diff":                 10,
        ]),
     ([      "quest":                "∑˜≥æ",
        "diff":                 3,
        ]),
     ([      "quest":                "∫⁄¡˙±ﬁ",
        "diff":                 2,
        ]),
     ([      "quest":                "°∫–«Àﬁ∂ææ≠°º…œ≤·°Ω°ª",
        "diff":                 2,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
