mapping *quest = ({
     ([      "quest":                "∑¸ƒßµ∂",
        "diff":                 10,
        ]),
     ([      "quest":                 "Ω∏’’÷" ,
        "diff":                 9,
        ]),
     ([      "quest":                BLK "»Ì‚¨º◊" NOR,
        "diff":                 8,
        ]),
     ([      "quest":                "√˜÷È",
        "diff":                 7,
        ]),
     ([      "quest":                HIW "”Ò∏´" NOR,
        "diff":                 6,
        ]),
     ([      "quest":                HIW "”Òµ∂" NOR,
        "diff":                 5,
        ]),
     ([      "quest":                HIW "Ã˙¬÷" NOR,
        "diff":                 4,
        ]),
     ([      "quest":                HIY  "Ω¬÷" NOR,
        "diff":                 4,
        ]),
     ([      "quest":                "°∏æ≈“ı’Êæ≠°πœ¬≤·",
        "diff":                 10,
        ]),
     ([      "quest":                "”Ò÷Ò’»",
        "diff":                 6,
        ]),
     ([      "quest":                MAG "¡È÷¨¿º" NOR,
        "diff":                 6,
        ]),
     ([      "quest":                "°∏æ≈“ı’Êæ≠°π…œ≤·",
        "diff":                 6,
        ]),
     ([      "quest":                "Ω–ªØº¶",
        "diff":                 6,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
