mapping *quest = ({
     ([      "quest":                "»¤·¨ôÂôÄ",
        "diff":                 10,
        ]),
     ([      "quest":                YEL "»Æ½ð¸«" NOR,
        "diff":                 9,
        ]),
     ([      "quest":                YEL "·ÉÍÕ½ð¼×" NOR,
        "diff":                 8,
        ]),
     ([      "quest":                HIW "Óñ¸«" NOR,
        "diff":                 7,
        ]),
     ([      "quest":                RED "ÑªÀÇ" NOR,
        "diff":                 6,
        ]),
     ([      "quest":                HIW "Óñ½£" NOR,
        "diff":                 5,
        ]),
     ([      "quest":                HIW "×êÊ¯" NOR,
        "diff":                 4,
        ]),
     ([      "quest":                HIG "ôä´ä" NOR,
        "diff":                 4,
        ]),
     ([      "quest":                HIW "½£ Æ×" NOR,
        "diff":                 10,
        ]),
     ([      "quest":                MAG "ÁéÖ¬À¼" NOR,
        "diff":                 6,
        ]),
     ([      "quest":                "Òø¹ÚÉßµ¨",
        "diff":                 6,
        ]),
     ([      "quest":                "½ð¹ÚÉßµ¨",
        "diff":                 6,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
