inherit SKILL;
mapping *quest = ({
      
        ([      "quest":                "¿µ¹ãÁê",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                3
        ]),
        ([      "quest":                "ËÕÐÇºÓ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                4
        ]),
 
        ([      "quest":                "°¢À­Ä¾º±",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             40,
                "score" :                6
        ]),
        ([      "quest":                "°¢À­Ä¾º±",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                7
        ]),
        ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                8
        ]),
        ([      "quest":                "°¢×Ï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                9
        ]),
  
        ([      "quest":                "¹ÈÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                12        
        ]),
        ([      "quest":                "·¥Ä¾µÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                13
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             160,
                "pot_bonus":             30,
                "score" :                14
        ]),
        ([      "quest":                "ÕÅÈý",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             80,
                "score" :                15
        ]),
        ([      "quest":                "½øÏã¿Í",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                16        
        ]),
        ([      "quest":                "Ð¡´ä",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                17
        ]),
        ([      "quest":                "ÖÆÏãµÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                18
        ]),
        ([      "quest":                "ÄªÉù¹È",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                19
        ]),
        ([      "quest":                "ËÎÔ¶ÇÅ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                20
        ]),
        ([      "quest":                "ÒóÀæÍ¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                21
        ]),
        ([      "quest":                "ÇåÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                22
        ]),
        ([      "quest":                "Óáá·ÑÒ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                23
        ]),
      
        ([      "quest":                "ÕÅ´äÉ½",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                27
        ]),
        ([      "quest":                "Öª¿ÍµÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :               28
        ]),
        ([      "quest":                "ÕÅËÉÏª",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                29
        ]),
        ([      "quest":                "ÓáÁ«ÖÛ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                30
        ]),
        ([      "quest":                "µÀÍ¯",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                31
        ]),
        ([      "quest":                "ÉñÁú½ÌÀÏÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                36
        ]),
        ([      "quest":                "ÊÝÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                37
        ]),
        ([      "quest":                "ÅÖÍ·ÍÓ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             280,
                "pot_bonus":             30,
                "score" :                38
        ]),
        ([      "quest":                "ÎÞ¸ùµÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                40
        ]),
        ([      "quest":                "ºé°²Í¨",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                41
        ]),
        ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             130,
                "pot_bonus":             30,
                "score" :                1
        ]),
        ([      "quest":                "Öñ½£",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             130,
                "pot_bonus":             30,
                "score" :                2
        ]),
        ([      "quest":                "ÎÚÀÏ´ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                3
        ]),
        ([      "quest":                "Ê¯É©",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             130,
                "pot_bonus":             30,
                "score" :                4
        ]),
        ([      "quest":                "ÃÉÃæÅ®ÀÉ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                5
        ]),
        ([      "quest":                "Ê¯É©",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                6
        ]),
        ([      "quest":                "À¼½£",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                7
        ]),
        ([      "quest":                "¾Õ½£",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             140,
                "pot_bonus":             30,
                "score" :                8
        ]),
        ([      "quest":                "·ûÃôÒÇ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                10        
        ]),
        ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                11        
       ]),
        ([      "quest":                "ÐéÖñ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                12       
        ]),
        ([      "quest":                "æ¾Å®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                22
        ]),
        ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                26    
           ]),
        ([      "quest":                "Ë½ÛÓÏÈÉú",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             250,
                "pot_bonus":            530,
                "score" :                30
        ]),
        ([      "quest":                "ÊØËÂÉ®±ø",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             50,
                "score" :                34
        ]),
        ([      "quest":                "ÐÐÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                35
        ]),
        ([      "quest":                "Ìô·ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                36
        ]),
        ([      "quest":                "³ÎÖ¾",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                37
        ]),
        ([      "quest":                "ÕÅµ­ÔÂ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                38
        ]),
        ([      "quest":                "ÇåÀÖ±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                40
        ]),
        ([      "quest":                "ÎÀÊ¿",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                42
        ]),
        ([      "quest":                "ÎéÇî",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                43
        ]),
        ([      "quest":                "Çå·¨±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                46
        ]),
        ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                47
        ]),
        ([      "quest":                "±¦Ïó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             50,
                "score" :                48
        ]),
        ([      "quest":                "ÄêÇáµÜ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                49
        ]),
        ([      "quest":                "µÀ¹ûìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             250,
                "pot_bonus":             30,
                "score" :                51
        ]),
        ([      "quest":                "À­ÕÂ»î·ð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             250,
                "pot_bonus":             30,
                "score" :                52
        ]),
        ([      "quest":                "ÂòÂôÌá",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                53
        ]),
        ([      "quest":                "ÕÂÀÏÈý",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                54
        ]),
        ([      "quest":                "ÈøÄ¾»î·ð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             250,
                "pot_bonus":             30,
                "score" :                55
        ]),
        ([      "quest":                "ÕÅ´äÉ½",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :               57
        ]),
        ([      "quest":                "³ÎÒâ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                58
        ]),
        ([      "quest":                "ÄêÇáµÜ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                59
        ]),
        ([      "quest":                "³ÎÖª",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                61
        ]),
        ([      "quest":                "³ÎÓû",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                62
        ]),
        ([      "quest":                "µÀÒ»ìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                63
        ]),
        ([      "quest":                "ÐÇËÞÅÉîàÊÖ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                64
        ]),
        ([      "quest":                "»ÛÃû×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                65
        ]),
        ([      "quest":                "²É»¨×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                66
        ]),
        ([      "quest":                "³ÎÐÐ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                67
        ]),
        ([      "quest":                "µÜ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                68
        ]),
        ([      "quest":                "³ÎÐÅ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                69
        ]),
        ([      "quest":                "³ÎÐÄ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                70
        ]),
        ([      "quest":                "³ÎË¼",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":            200,
                "pot_bonus":             30,
                "score" :                71
        ]),
        ([      "quest":                "³ÎÊ¶",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                72
        ]),
        ([      "quest":                "³ÎÉÐ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                73
        ]),
        ([      "quest":                "³ÎÃ÷",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                74
        ]),
        ([      "quest":                "³ÎÃð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                75
        ]),
        ([      "quest":                "³ÎÁé",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :               76
        ]),
        ([      "quest":                "´ïÄ¦×æÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             400,
                "pot_bonus":             50,
                "score" :                79
        ]),
        ([      "quest":                "°ÍÒÀ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                83
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                84
        ]),
        ([      "quest":                "»ÛÈç×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                85
        ]),
        ([      "quest":                "»Û¿Õ×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                86
        ]),
        ([      "quest":                "»ÛÉ«×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                87
        ]),
        ([      "quest":                "»Û½à×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                88
        ]),
        ([      "quest":                "¹¶¶Á",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                89
        ]),
        ([      "quest":                "·ë°¢Èý",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                90
        ]),
        ([      "quest":                "»ÛºÏ×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                91
        ]),
        ([      "quest":                "ÇåÔµ±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             210,
                "pot_bonus":             30,
                "score" :                92
        ]),
        ([      "quest":                "ÇåÏþ±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                93
        ]),
        ([      "quest":                "ÇåÎÞ±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                94
        ]),
        ([      "quest":                "ÀËÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                95
        ]),
        ([      "quest":                "ÃÉÃæÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :               97
        ]),
        ([      "quest":                "·¥Ä¾µÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                98
        ]),
        ([      "quest":                "³Î¾»",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                99
        ]),
        ([      "quest":                "ÓÎ·½ºÍÉÐ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                100        
               ]),
        ([      "quest":                "³Î¼á",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                101       
               ]),
        ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                102
        ]),
        ([      "quest":                "³Î¼Å",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                103
        ]),
        ([      "quest":                "°¢À­Ä¾º±",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                104
        ]),
        ([      "quest":                "µÀÕýìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                105
        ]),
        ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                106        
        ]),
        ([      "quest":                "³ÎºÍ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                108        
        ]),
        ([      "quest":                "³Î¹Û",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                109        
        ]),
        ([      "quest":                "µÀÏóìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                110        
        ]),
        ([      "quest":                "µÀÏàìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                111
        ]),
        ([      "quest":                "½£¿Í",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                112       
        ]),
        ([      "quest":                "½­°ÙÊ¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                113
        ]),
        ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                114
        ]),
        ([      "quest":                "ÇåÉÆ±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             160,
                "pot_bonus":             30,
                "score" :                115
        ]),
        ([      "quest":                "µÀÆ·ìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             210,
                "pot_bonus":             30,
                "score" :                116
        ]), 
        ([      "quest":                "ÄªÉù¹È",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                117
        ]),
        ([      "quest":                "µÀ³ÉìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                118        
        ]),
        ([      "quest":                "µÀ¾õìøÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                120        
       ]),
        ([      "quest":                "²¨Ë¹ÉÌÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                121        
        ]),
        ([      "quest":                "ÓáÁ«ÖÛ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                122
        ]),
        ([      "quest":                "¶¡´ºÇï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             250,
                "pot_bonus":             30,
                "score" :                123
        ]),
        ([      "quest":                "Å®º¢",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                124
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                126
        ]),
        ([      "quest":                "ÊéÉú",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                127
        ]),
        ([      "quest":                "Ìô·ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":                    30,
                "score" :                128
        ]),
        ([      "quest":                "»ÛÕæ×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             400,
                "pot_bonus":             80,
                "score" :                129
        ]),
        ([      "quest":                "Â½¸ßÐù",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             170,
                "pot_bonus":             30,
                "score" :                130
        ]),
        ([      "quest":                "ºé°²Í¨",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             30,
                "score" :                131        
        ]),
        ([      "quest":                "ÌË×ÓÊÖ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                134        
        ]),
        ([      "quest":                "ÌìÀÇ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                135
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                136
        ]),
        ([      "quest":                "Ê¨ºð×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                137
        ]),
        ([      "quest":                "ÐÇËÞÅÉ¹ÄÊÖ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                138
        ]),
        ([      "quest":                "»ÛÐÞ×ðÕß",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                139
        ]),
        ([      "quest":                "ÇåÎª±ÈÇð",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                140        
       ]),
        ([      "quest":                "ÐéÃ÷",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                141
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                5
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                7
        ]),
        ([      "quest":                "ÄÁÑòÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             160,
                "pot_bonus":             50,
                "score" :                8
        ]),
        ([      "quest":                "ÄÁÑòÅ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                10        
        ]),
       ([      "quest":                "ÉÙÅ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                19
        ]),
        ([      "quest":                "ÉñÅ©°ïµÜ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                20
        ]),
        ([      "quest":                "É®ÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                21
        ]),
        ([      "quest":                "Óæ·ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                23
        ]),
        ([      "quest":                "ÓÎ¿Í",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                24
        ]),
        ([      "quest":                "Ñ¦ÀÏ°å",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                26    
        ]),
        ([      "quest":                "Öìµ¤³¼",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                27
        ]),
        ([      "quest":                "ñÒÍòÀï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :               28
        ]),
        ([      "quest":                "Ð¡µÀ¹Ã",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             170,
                "pot_bonus":             30,
                "score" :                29
        ]),
        ([      "quest":                "½øÏã¿Í",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                30
        ]),
        ([      "quest":                "»¤ËþÉ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                35
        ]),
        ([      "quest":                "ÀÏÄêÉ®ÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             70,
                "score" :                36
        ]),
        ([      "quest":                "Ð¡É³ÃÖ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                37
        ]),
        ([      "quest":                "»¤ËÂÉ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                38
        ]),
        ([      "quest":                "ÉÕ·¹É®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                39
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                44
        ]),
        ([      "quest":                "»¤É½µÀÊ¿",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             60,
                "score" :                45
        ]),
        ([      "quest":                "µÀÍ¯",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                46
        ]),
        ([      "quest":                "ºÂ´óÍ¨",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             80,
                "score" :                47
        ]),
        ([      "quest":                "ÍÁ·Ë",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :               57
        ]),
        ([      "quest":                "ÍÁ·ËÍ·",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                58
        ]),
        ([      "quest":                "ÒüÖ¾Æ½",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                59
        ]),
        ([      "quest":                "ÕÆÒ©µÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             250,
                "pot_bonus":             30,
                "score" :                60
        ]),
        ([      "quest":                "ÑÆÆÍ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                63
        ]),
        ([      "quest":                "ÊÌÍ¯",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                65
        ]),
        ([      "quest":                "ÆÍÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                66
        ]),
        ([      "quest":                "Â½³Ë·ç",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                67
        ]),
        ([      "quest":                "ñÔÅ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                68
        ]),
        ([      "quest":                "»ÆÒ©Ê¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             50,
                "score" :                69
        ]),
        ([      "quest":                "Â½¹ÚÓ¢",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                70
        ]),
        ([      "quest":                "ÇúÁé·ç",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                71
        ]),
        ([      "quest":                "»ÆÈØ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                72
        ]),
        ([      "quest":                "³øÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :               76
        ]),
        ([      "quest":                "Ë¾Âí´ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                77
        ]),
        ([      "quest":                "¶«·½²»°Ü",
                "quest_type":           "É±",
                "time":                  1000,
                "exp_bonus":             99300,
                "pot_bonus":             80,
                "score" :                78
        ]),
        ([      "quest":                "¼Ö²¼",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                80
        ]),
        ([      "quest":                "À¶·ï»Ë",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                81
        ]),
        ([      "quest":                "Í¯°ÙÐÜ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                93
        ]),
        ([      "quest":                "Íõ³Ç",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                94
        ]),
        ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             70,
                "score" :                96
        ]),
        ([      "quest":                "ÑîÁ«Í¤",
                "quest_type":           "É±",
                "time":                  9400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :               97
        ]),
        ([      "quest":                "ÈÎÓ¯Ó¯",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             60,
                "score" :                99
        ]),
        ([      "quest":                "ÔÀÁéÉº",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             140,
                "pot_bonus":             30,
                "score" :                104
        ]),
        ([      "quest":                "Áº·¢",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             140,
                "pot_bonus":             30,
                "score" :                105
        ]),
        ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             140,
                "pot_bonus":             30,
                "score" :                106        
        ]),
        ([      "quest":                "½­ºþºÀ¿Í",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                107
        ]),
        ([      "quest":                "¸ß¸ùÃ÷",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                108       
       ]),
        ([      "quest":                "Â½´óÓÐ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                109        
              ]),
        ([      "quest":                "ÀîÌú×ì",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                110        
               ]),
        ([      "quest":                "Ê©´÷×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                111
        ]),
        ([      "quest":                "Áîºü³å",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             50,
                "score" :                113
        ]),
        ([      "quest":                "ÄþÖÐÔò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             50,
                "score" :                114
        ]),
        ([      "quest":                "ÎÞ³¾µÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                119
        ]),
        ([      "quest":                "°àÊçæµ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             30,
                "score" :                118       
             ]),
        ([      "quest":                "ºÎÌ«³å",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":              300,
                "pot_bonus":             60,
                "score" :                121       
              ]),
              ([      "quest":                "À¥ÂØÅÉµÜ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             130,
                "pot_bonus":             30,
                "score" :                123
        ]),
        ([      "quest":                "Î÷»ª×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             130,
                "pot_bonus":             30,
                "score" :                124
        ]),
        ([      "quest":                "ÆÍÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                125
        ]),
        ([      "quest":                "¼ò³¤ÀÏ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                130
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             300,
                "pot_bonus":             70,
                "score" :                131        
              ]),
        ([      "quest":                "Áº³¤ÀÏ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             190,
                "pot_bonus":             30,
                "score" :                135
        ]),
        ([      "quest":                "ÀèÉú",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                136
        ]),
        ([      "quest":                "ÕÅÈý",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                2
        ]),
        ([      "quest":                "Ò©ÆÌ»ï¼Æ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                3
        ]),
        ([      "quest":                "ÍõÎå",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                4
        ]),
        ([      "quest":                "¹Ü¼Ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                5
        ]),
        ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                6
        ]),
        ([      "quest":                "ÀÏ´¬·ò",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                8
        ]),
        ([      "quest":                "³ÌÒ©·¢",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                9
        ]),
        ([      "quest":                "ÀÏ²Ã·ì",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                10       
        ]),
        ([      "quest":                "¹Ù±ø",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                11        
        ]),
        ([      "quest":                "ïÚÍ·",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                12        
        ]),
        ([      "quest":                "°¢ÇìÉ©",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                13
        ]),
        ([      "quest":                "Ç®ÑÛ¿ª",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                14
        ]),
        ([      "quest":                "Á÷Ã¥Í·",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                15
        ]),
        ([      "quest":                "Á÷Ã¥",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                16        
        ]),
        ([      "quest":                "ÁÖÕðÄÏ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                17
        ]),
        ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                18
        ]),
        ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                19
        ]),
        ([      "quest":                "ÌÆéª",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                20
        ]),
        ([      "quest":                "Î¤´º·¼",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                21
        ]),
        ([      "quest":                "Ñ²²¶",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             40,
                "score" :                22
        ]),
        ([      "quest":                "Öì´Ï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             60,
                "score" :                23
        ]),
        ([      "quest":                "Öììä",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                24
        ]),
        ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                26    
        ]),
        ([      "quest":                "ÑÃÒÛ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                27
        ]),
        ([      "quest":                "ÑîÓÀ¸£",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :               28
        ]),
        ([      "quest":                "Ð¡¹ð×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                29
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                30
        ]),
        ([      "quest":                "ÙþÀÏ°å",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                31
        ]),
        ([      "quest":                "Îä½«",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                32   
     ]),
        ([      "quest":                "Ìú½³",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                33
        ]),
        ([      "quest":                "Ì·ÓÑ¼Í",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                34
        ]),
        ([      "quest":                "Ê·ÇàÉ½",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             40,
                "score" :                35
        ]),
        ([      "quest":                "Ç®ÑÛ¿ª",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                36
        ]),
        ([      "quest":                "Æ½Ò»Ö¸",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                37
        ]),
        ([      "quest":                "Ã©Ê®°Ë",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                38
        ]),
        ([      "quest":                "Âí³¬ÐË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                39
        ]),
        ([      "quest":                "Ê·ËÉ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                40
        ]),
        ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                41
        ]),
        ([      "quest":                "³ÌÀÏ°å",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                42
        ]),
        ([      "quest":                "×¯·òÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             45,
                "score" :                43
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                44
        ]),
        ([      "quest":                "ÉñÁú½ÌµÜ×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                45
        ]), 
        ([      "quest":                "¶À±ÛÉñÄá",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             380,
                "pot_bonus":             50,
                "score" :                46
        ]),
        ([      "quest":                "³øÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                47
        ]),
        ([      "quest":                "¹ËÑ×Îä",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                49
        ]),
        ([      "quest":                "¹Ø°²»ù",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             120,
                "pot_bonus":             30,
                "score" :                50
        ]),
        ([      "quest":                "¹ÛÖÚ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                51
        ]),
        ([      "quest":                "ºúÕÆ¹ñ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                52
        ]),
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                53
        ]),
        ([      "quest":                "Ò©ÆÌ»ï¼Æ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                54
        ]),
        ([      "quest":                "¼ÖÀÏÁù",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                55
        ]),
        ([      "quest":                "ÊÌÎÀ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :               57
        ]),
        ([      "quest":                "ÀÏð±ÆÅ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                58
        ]),
        ([      "quest":                "ÀîÁ¦ÊÀ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             130,
                "pot_bonus":             30,
                "score" :                59
        ]),
        ([      "quest":                "Ð¡Á÷Ã¥",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                60
        ]),
        ([      "quest":                "ÆÍÒÛ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                61
        ]),
        ([      "quest":                "ÆëÔª¿­",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             40,
                "score" :                62
        ]),
        ([      "quest":                "Ç®ÀÏ±¾",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                63
        ]),
        ([      "quest":                "ÉñÕÕÉÏÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             40,
                "score" :                64
        ]),
        ([      "quest":                "Ë«¶ù",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                65
        ]),
        ([      "quest":                "ÊéÍ¯",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             190,
                "pot_bonus":             50,
                "score" :                66
        ]),
        ([      "quest":                "Ìú½³",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                67
        ]),
        ([      "quest":                "ÎâÖ®ÈÙ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             30,
                "score" :                68
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                69
        ]),
        ([      "quest":                "Ð¡··",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                70
        ]),
        ([      "quest":                "Ï·×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                71
        ]),
        ([      "quest":                "ÐìÌì´¨",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                72
        ]),
        ([      "quest":                "³Â½üÄÏ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             220,
                "pot_bonus":             30,
                "score" :                74
        ]),
        ([      "quest":                "ÐþÕæµÀ³¤",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             200,
                "pot_bonus":             40,
                "score" :                75
        ]),
        ([      "quest":                "¹±ÌÆ²Ö¹úÊ¦",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             240,
                "pot_bonus":             50,
                "score" :                77
        ]),
        ([      "quest":                "¹Ñ¸¾",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                80
        ]),
        ([      "quest":                "´å¹Ã",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                82
        ]),
        ([      "quest":                "ÊËÎÀ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                83
        ]),
        ([      "quest":                "É½ÔôÍ·",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                84
        ]),
        ([      "quest":                "É½Ôô",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                85
        ]),
        ([      "quest":                "»¨»¨¹«×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             160,
                "pot_bonus":             40,
                "score" :                88
        ]),
        ([      "quest":                "ÃÅÎÀ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                89
        ]),
        ([      "quest":                "Å©Ãñ",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                90
        ]),
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                91
        ]),
        ([      "quest":                "ÀÏ²Ä",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                92
        ]),
        ([      "quest":                "Ð¡º¢",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                93
        ]), 
        ([      "quest":                "½ð»¨",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             150,
                "pot_bonus":             40,
                "score" :                94
        ]),
        ([      "quest":                "¹Ñ¸¾",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                95
        ]),
        ([      "quest":                "ÕÅÂè",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                96
        ]),
        ([      "quest":                "Ð¡Çà",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             160,
                "pot_bonus":             50,
                "score" :                98
        ]),
        ([      "quest":                "°×ÒÂÉÙÅ®",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                99
        ]),
        ([      "quest":                "ÅãÁ·Í¯×Ó",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                101       
              ]),
        ([      "quest":                "ÎèÉßÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                102
        ]),
        ([      "quest":                "´å¸¾",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                105
        ]),
        ([      "quest":                "²ÉËñÈË",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             180,
                "pot_bonus":             30,
                "score" :                107
        ]),
        ([      "quest":                "Ê¿±ø",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                110        
        ]),
         ([      "quest":                "¸µË¼¹é",
                "quest_type":           "É±",
                "time":                  400,
                "exp_bonus":             100,
                "pot_bonus":             30,
                "score" :                124
        ]),
      
 });
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
